### ISSUE TITLE
Use new translation system throughout codebase

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#152]
**Current situation**
Only some of our components and content are using the new translation system.

**Desired situation**
The entire app should use the new translations system.

**Notes**
Let's first complete #148 before we pick this up, should be easier to test this that way.

I've provided some examples in `components/translations.ts` for the `Hero.tsx` component.
For content you can take a look at `content/genesis/genesis-1/translations.ts`

**Comment by benalleng** [comment]
The translation system is almost there! with #245 and #279 now merged into master, many of the translation bugs we encounter have now been solved.
We are still dealing with two things moving forward.
- [x] #256 flashing white screen following a language switch after loading the page
- [x] #250 both languages visible in the same render 
- [ ] There is no easily accessible language selection, addressed by #148
- [ ] #313 Upon clicking a link the locale will always switch back to the default `/en` url and load the english language
There are two ways to solve this IMO

**Comment by ecurrencyhodler** [comment]
@afterburn Do you 2 pr's close this issue out?
